name: Deploy Vite Vue3 App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 根据你的项目需求调整 Node.js 版本
          cache: 'npm'      # 使用 npm 缓存，加速依赖安装

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # Step 4: 构建项目
      - name: Build project
        run: npm run build

      # Step 5: 使用 SCP 将构建产物上传到服务器
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "dist/*"
          target: ${{ secrets.TARGET_DIR}} # 服务器上的目标目录
          strip_components: 1
          args: "--overwrite"

      # 可选：重启服务或执行额外命令
#      - name: Restart server (optional)
#        run: ssh -i ${{ secrets.SERVER_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo systemctl restart nginx"
